image: docker.slock.it/build-images/node:10-alpine

stages:
  - build
  - deploy

build-pkg:
  stage: build
  tags:
    - short-jobs
  script:
    - sh /prepare.sh

  artifacts:
    name: build-js
    paths:
      - build/

push-to-registry:
  stage: deploy
  tags:
    - short-jobs
  only: # deploy only on  semantic versions tags
    - /^v[0-9]*\.[0-9]*\.[0-9]*-?.*$/
  except:
    - branches
  dependencies:
    - build-pkg
  script:
    - sh /prepare.sh
    - npm --no-git-tag-version -f version $CI_COMMIT_TAG
    - npm publish
