sudo: required
dist: trusty
language: node_js
node_js:
  - '10.0.0'

install:
  - npm install
  - npm run install-contracts
  - npm run compile
 
script:
  - npm run lint
  - npm run build-ts
  - npm test